
// From https://en.wikipedia.org/wiki/List_of_sovereign_states
export const countries = [
    { name: "Afghanistan", title: "Islamic Republic of Afghanistan" },
    { name: "Albania", title: "Republic of Albania" },
    { name: "Algeria", title: "People's Democratic Republic of Algeria" },
    { name: "Andorra", title: "Principality of Andorra" },
    { name: "Angola", title: "Republic of Angola" },
    { name: "Antigua and Barbuda" },
    { name: "Argentina", title: "Argentine Republic" },
    { name: "Armenia", title: "Republic of Armenia" },
    { name: "Australia", title: "Commonwealth of Australia" },
    { name: "Austria", title: "Republic of Austria" },
    { name: "Azerbaijan", title: "Republic of Azerbaijan" },
    { name: "The Bahamas", title: "Commonwealth of The Bahamas" },
    { name: "Bahrain", title: "Kingdom of Bahrain" },
    { name: "Bangladesh", title: "People's Republic of Bangladesh" },
    { name: "Barbados" },
    { name: "Belarus", title: "Republic of Belarus" },
    { name: "Belgium", title: "Kingdom of Belgium" },
    { name: "Belize" },
    { name: "Benin", title: "Republic of Benin" },
    { name: "Bhutan", title: "Kingdom of Bhutan" },
    { name: "Bolivia", title: "Plurinational State of Bolivia" },
    { name: "Bosnia and Herzegovina" },
    { name: "Botswana", title: "Republic of Botswana" },
    { name: "Brazil", title: "Federative Republic of Brazil" },
    { name: "Brunei", title: "Nation of Brunei, the Abode of Peace" },
    { name: "Bulgaria", title: "Republic of Bulgaria" },
    { name: "Burkina Faso" },
    { name: "Burundi", title: "Republic of Burundi" },
    { name: "Cambodia", title: "Kingdom of Cambodia" },
    { name: "Cameroon", title: "Republic of Cameroon" },
    { name: "Canada" },
    { name: "Cape Verde", title: "Republic of Cabo Verde" },
    { name: "Central African Republic" },
    { name: "Chad", title: "Republic of Chad" },
    { name: "Chile", title: "Republic of Chile" },
    { name: "China", title: "People's Republic of China" },
    { name: "Colombia", title: "Republic of Colombia" },
    { name: "Comoros", title: "Union of the Comoros" },
    { name: "Democratic Republic of the Congo" },
    { name: "Republic of the Congo" },
    { name: "Costa Rica", title: "Republic of Costa Rica" },
    { name: "Croatia", title: "Republic of Croatia" },
    { name: "Cuba", title: "Republic of Cuba" },
    { name: "Cyprus", title: "Republic of Cyprus" },
    { name: "Czech Republic" },
    { name: "Denmark", title: "Kingdom of Denmark" },
    { name: "Djibouti", title: "Republic of Djibouti" },
    { name: "Dominica", title: "Commonwealth of Dominica" },
    { name: "Dominican Republic" },
    { name: "East Timor", title: "Democratic Republic of Timor-Leste" },
    { name: "Ecuador", title: "Republic of Ecuador" },
    { name: "Egypt", title: "Arab Republic of Egypt" },
    { name: "El Salvador", title: "Republic of El Salvador" },
    { name: "Equatorial Guinea", title: "Republic of Equatorial Guinea" },
    { name: "Eritrea", title: "State of Eritrea" },
    { name: "Estonia", title: "Republic of Estonia" },
    { name: "Eswatini", title: "Kingdom of Eswatini" },
    { name: "Ethiopia", title: "Federal Democratic Republic of Ethiopia" },
    { name: "Fiji", title: "Republic of Fiji" },
    { name: "Finland", title: "Republic of Finland" },
    { name: "France", title: "French Republic" },
    { name: "Gabon", title: "Gabonese Republic" },
    { name: "The Gambia", title: "Republic of The Gambia" },
    { name: "Georgia" },
    { name: "Germany", title: "Federal Republic of Germany" },
    { name: "Ghana", title: "Republic of Ghana" },
    { name: "Greece", title: "Hellenic Republic" },
    { name: "Grenada" },
    { name: "Guatemala", title: "Republic of Guatemala" },
    { name: "Guinea", title: "Republic of Guinea" },
    { name: "Guinea-Bissau", title: "Republic of Guinea-Bissau" },
    { name: "Guyana", title: "Co-operative Republic of Guyana" },
    { name: "Haiti", title: "Republic of Haiti" },
    { name: "Honduras", title: "Republic of Honduras" },
    { name: "Hungary" },
    { name: "Iceland" },
    { name: "India", title: "Republic of India" },
    { name: "Indonesia", title: "Republic of Indonesia" },
    { name: "Iran", title: "Islamic Republic of Iran" },
    { name: "Iraq", title: "Republic of Iraq" },
    { name: "Ireland" },
    { name: "Israel" },
    { name: "Italy", title: "Italian Republic" },
    { name: "Ivory Coast", title: "Republic of Côte d'Ivoire" },
    { name: "Jamaica" },
    { name: "Japan" },
    { name: "Jordan", title: "Hashemite Kingdom of Jordan" },
    { name: "Kazakhstan", title: "Republic of Kazakhstan" },
    { name: "Kenya", title: "Republic of Kenya" },
    { name: "Kiribati", title: "Republic of Kiribati" },
    { name: "North Korea", title: "Democratic People's Republic of Korea" },
    { name: "South Korea", title: "Republic of Korea" },
    { name: "Kuwait", title: "State of Kuwait" },
    { name: "Kyrgyzstan", title: "Kyrgyz Republic" },
    { name: "Laos", title: "Lao People's Democratic Republic" },
    { name: "Latvia", title: "Republic of Latvia" },
    { name: "Lebanon", title: "Lebanese Republic" },
    { name: "Lesotho", title: "Kingdom of Lesotho" },
    { name: "Liberia", title: "Republic of Liberia" },
    { name: "Libya", title: "State of Libya" },
    { name: "Liechtenstein", title: "Principality of Liechtenstein" },
    { name: "Lithuania", title: "Republic of Lithuania" },
    { name: "Luxembourg", title: "Grand Duchy of Luxembourg" },
    { name: "Madagascar", title: "Republic of Madagascar" },
    { name: "Malawi", title: "Republic of Malawi" },
    { name: "Malaysia" },
    { name: "Maldives", title: "Republic of Maldives" },
    { name: "Mali", title: "Republic of Mali" },
    { name: "Malta", title: "Republic of Malta" },
    { name: "Marshall Islands", title: "Republic of the Marshall Islands" },
    { name: "Mauritania", title: "Islamic Republic of Mauritania" },
    { name: "Mauritius", title: "Republic of Mauritius" },
    { name: "Mexico", title: "United Mexican States" },
    { name: "Federated States of Micronesia " },
    { name: "Moldova", title: "Republic of Moldova" },
    { name: "Monaco", title: "Principality of Monaco" },
    { name: "Mongolia" },
    { name: "Montenegro" },
    { name: "Morocco", title: "Kingdom of Morocco" },
    { name: "Mozambique", title: "Republic of Mozambique" },
    { name: "Myanmar", title: "Republic of the Union of Myanmar" },
    { name: "Namibia", title: "Republic of Namibia" },
    { name: "Nauru", title: "Republic of Nauru" },
    { name: "Nepal", title: "Federal Democratic Republic of Nepal" },
    { name: "Netherlands", title: "Kingdom of the Netherlands" },
    { name: "New Zealand" },
    { name: "Nicaragua", title: "Republic of Nicaragua" },
    { name: "Niger", title: "Republic of Niger" },
    { name: "Nigeria", title: "Federal Republic of Nigeria" },
    { name: "North Macedonia", title: "Republic of North Macedonia" },
    { name: "Norway", title: "Kingdom of Norway" },
    { name: "Oman", title: "Sultanate of Oman" },
    { name: "Pakistan", title: "Islamic Republic of Pakistan" },
    { name: "Palau", title: "Republic of Palau" },
    { name: "Palestine", title: "State of Palestine" },
    { name: "Panama", title: "Republic of Panama" },
    { name: "Papua New Guinea", title: "Independent State of Papua New Guinea" },
    { name: "Paraguay", title: "Republic of Paraguay" },
    { name: "Peru", title: "Republic of Peru" },
    { name: "Philippines", title: "Republic of the Philippines" },
    { name: "Poland", title: "Republic of Poland" },
    { name: "Portugal", title: "Portuguese Republic" },
    { name: "Qatar", title: "State of Qatar" },
    { name: "Romania" },
    { name: "Russia", title: "Russian Federation" },
    { name: "Rwanda", title: "Republic of Rwanda" },
    { name: "Saint Kitts and Nevis", title: "Federation of Saint Christopher and Nevis" },
    { name: "Saint Lucia" },
    { name: "Saint Vincent and the Grenadines" },
    { name: "Samoa", title: "Independent State of Samoa" },
    { name: "San Marino", title: "Republic of San Marino" },
    { name: "São Tomé and Príncipe", title: "Democratic Republic of São Tomé and Príncipe" },
    { name: "Saudi Arabia", title: "Kingdom of Saudi Arabia" },
    { name: "Senegal", title: "Republic of Senegal" },
    { name: "Serbia", title: "Republic of Serbia" },
    { name: "Seychelles", title: "Republic of Seychelles" },
    { name: "Sierra Leone", title: "Republic of Sierra Leone" },
    { name: "Singapore", title: "Republic of Singapore" },
    { name: "Slovakia", title: "Slovak Republic" },
    { name: "Slovenia", title: "Republic of Slovenia" },
    { name: "Solomon Islands" },
    { name: "Somalia", title: "Federal Republic of Somalia" },
    { name: "South Africa", title: "Republic of South Africa" },
    { name: "South Sudan", title: "Republic of South Sudan" },
    { name: "Spain", title: "Kingdom of Spain" },
    { name: "Sri Lanka", title: "Democratic Socialist Republic of Sri Lanka" },
    { name: "Sudan", title: "Republic of the Sudan" },
    { name: "Suriname", title: "Republic of Suriname" },
    { name: "Sweden", title: "Kingdom of Sweden" },
    { name: "Switzerland", title: "Swiss Confederation" },
    { name: "Syria", title: "Syrian Arab Republic" },
    { name: "Tajikistan", title: "Republic of Tajikistan" },
    { name: "Tanzania", title: "United Republic of Tanzania" },
    { name: "Thailand", title: "Kingdom of Thailand" },
    { name: "Togo", title: "Togolese Republic" },
    { name: "Tonga", title: "Kingdom of Tonga" },
    { name: "Trinidad and Tobago", title: "Republic of Trinidad and Tobago" },
    { name: "Tunisia", title: "Republic of Tunisia" },
    { name: "Turkey", title: "Republic of Turkey" },
    { name: "Turkmenistan" },
    { name: "Tuvalu" },
    { name: "Uganda", title: "Republic of Uganda" },
    { name: "Ukraine" },
    { name: "United Arab Emirates" },
    { name: "United Kingdom", title: "United Kingdom of Great Britain and Northern Ireland" },
    { name: "United States", title: "United States of America" },
    { name: "Uruguay", title: "Oriental Republic of Uruguay" },
    { name: "Uzbekistan", title: "Republic of Uzbekistan" },
    { name: "Vanuatu", title: "Republic of Vanuatu" },
    { name: "Vatican City", title: "Vatican City State" },
    { name: "Venezuela", title: "Bolivarian Republic of Venezuela" },
    { name: "Vietnam", title: "Socialist Republic of Vietnam" },
    { name: "Yemen", title: "Republic of Yemen" },
    { name: "Zambia", title: "Republic of Zambia" },
    { name: "Zimbabwe", title: "Republic of Zimbabwe" }
];
